### ISSUE TITLE
jstree-bootstrap-theme wrong dependencies

### ISSUE THREAD

**Issue by ptahchiev** [webjars/jstree#21]
The jstree-bootstrap-theme depends on `org.webjars.bower:jstree:[3.0.4,3.1)`:
http://repo1.maven.org/maven2/org/webjars/bower/jstree-bootstrap-theme/1.0.1/jstree-bootstrap-theme-1.0.1.pom

However on maven central none of the versions match this:
http://repo1.maven.org/maven2/org/webjars/bower/jstree/

**Comment by jamesward** [comment]
I've deployed the Bower WebJar `org.webjars.bower:jstree:3.0.` via https://www.webjars.org/

In the future if there are missing non-Classic WebJar deps, you should be able to deploy them on your own via https://www.webjars.org/
